set nocompatible

" line no
set nu
set relativenumber

" look
colo desert
set cursorline

" syntax highlight
syntax on

" tab
set softtabstop=4
set tabstop=4
set shiftwidth=4
set smartindent
set incsearch
set autoindent
set expandtab

" mouse
set mouse=a

" backspace can't use
set backspace=indent,eol,start

filetype plugin indent on

if has("win32")
    set encoding=utf-8
    source $VIMRUNTIME/delmenu.vim
    " source $VIMRUNTIME/menu.vim
    set guifont=Source_Code_Pro_for_Powerline:h10:cANSI
endif

au FileType json set ts=2 sts=2 sw=2 expandtab
au FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

