set nocompatible

" line no
set nu
set relativenumber

" look
colo desert
set cursorline

" syntax highlight
syntax on

" tab
set softtabstop=4
set tabstop=4
set shiftwidth=4
set smartindent
set incsearch
set autoindent
set expandtab

filetype plugin indent on

if has("win32")
    set encoding=utf-8
    source $VIMRUNTIME/delmenu.vim
    " source $VIMRUNTIME/menu.vim
    set guifont=Source_Code_Pro_for_Powerline:h10:cANSI
endif

" Set vundle as vim filetype
au BufRead,BufNewFile vundle set filetype=vim
